const FILTERS_CONFIG = ({ brands, models, searchParams }) => [
  {
    title: "Brand",
    field: "brand",
    queryParam: "brand_id",
    type: "select",
    options: brands,
    value: searchParams.get("brand_id") || "",
    placeholder: "Select a brand",
    filterFn: (value) => value === searchParams.get("brand_id"),
  },
  {
    title: "Model",
    field: "model",
    queryParam: "model",
    type: "select",
    options: models,
    value: searchParams.get("model") || "",
    placeholder: "Select a model",
    filterFn: (value) => value === searchParams.get("model"),
  },
  {
    title: "Year from",
    field: "year",
    queryParam: "year_from",
    type: "select",
    options: [
      { title: 2018, value: 2018 },
      2019,
      2020,
      2021,
      2022,
      2023,
      2024,
      2025,
    ],
    value: searchParams.get("year_from") || "",
    placeholder: "From",
    filterFn: (value) => value >= searchParams.get("year_from"),
  },
  {
    title: "Year to",
    field: "year",
    queryParam: "year_to",
    type: "select",
    options: [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    value: searchParams.get("year_to") || "",
    placeholder: "To",
    filterFn: (value) => value <= searchParams.get("year_to"),
  },
];

export default FILTERS_CONFIG;
